var sound1="java编程";
var sound2="asp.net软件开发";
var sound3="嵌入式开发";
var sound4="数据库基础教程";
var sound5="oracle数据库开发";
var sound6="mysql数据库教程";
var sound7="c++基础入门";
var sound8="c#面试题";
var sound9="Ajax无刷新";
var sound10="sql server";
var sound11="数据库存储过程";
var sound12="asp.net 2005软件开发";
var sound13="div+css教程";
var sound14="ado.net基础教程";
var sound15="linux基础教程";
var sound16="xml入门教程";
var sound17="javascript与ajax教程";
var sound18="c#基础教程";
var sound19="java基础教程";
var sound20="java入门教程";
var sound21="软件开发";
var sound22="java软件开发";
var sound23="c++软件开发";
var x=Math.round(Math.random()*22);
if (x==0) x=sound1;
else if (x==1) x=sound2;
else if (x==2) x=sound3;
else if (x==3) x=sound4;
else if (x==4) x=sound5;
else if (x==5) x=sound6;
else if (x==6) x=sound7;
else if (x==7) x=sound8;
else if (x==8) x=sound9;
else if (x==9) x=sound10;
else if (x==10) x=sound11;
else if (x==11) x=sound12;
else if (x==12) x=sound13;
else if (x==13) x=sound14;
else if (x==14) x=sound15;
else if (x==15) x=sound16;
else if (x==16) x=sound17;
else if (x==17) x=sound18;
else if (x==18) x=sound19;
else if (x==19) x=sound20;
else if (x==20) x=sound21;
else if (x==21) x=sound22;
else x=sound23;
document.getElementById("f1").value=x;
