var s_footer="";
s_footer += "<style>";
s_footer += "#CFContent a:link {";
s_footer += "	color: #000;";
s_footer += "	text-decoration: none;";
s_footer += "}";
s_footer += "#CFContent a:visited {";
s_footer += "	color: #000;";
s_footer += "	text-decoration: none;";
s_footer += "}";
s_footer += "#CFContent a:hover {";
s_footer += "	color: #F00;";
s_footer += "	text-decoration: underline;";
s_footer += "}";
s_footer += "#CFContent a:active {";
s_footer += "	color: #000;";
s_footer += "	text-decoration: none;";
s_footer += "}";
s_footer += "	#CFBig {";
s_footer += "		width: 760px;";
s_footer += "		clear: both;";
s_footer += "		margin: auto;";
s_footer += "		font-family: Tahoma, sans-serif;";
s_footer += "		text-align: center;background-color: #FFF;";
s_footer += "	}	";
s_footer += "	#CFBig #CFContent {";
s_footer += "		margin: auto;";
s_footer += "		width: 500px;";
s_footer += "		text-align: center;";
s_footer += "	}";
s_footer += "	#CFBig #CFContent p {";
s_footer += "		margin: 2px;font-size:9pt; ";
s_footer += "	}";
s_footer += "	#CFBig hr {";
s_footer += "		height: 1px;";
s_footer += "		color: #4682B4;";
s_footer += "	}";
s_footer += "	#CFBig #CFBiaoShi {";
s_footer += "		width: 40px;";
s_footer += "		float: right;";
s_footer += "	}	";
s_footer += "</style>";
s_footer += "<div id=\"CFBig\" align=center>";
s_footer += "	<hr align=\"center\" />";
s_footer += "	<div id=\"CFContent\">";
s_footer += "		<div id=\"CFBiaoShi\"><a href=\"http://www.hd315.gov.cn/beian/view.asp?bianhao=010202001032100010\"><img src=\"http://www.csdn.net/CSDN_Common_Header_Footer/Images/BiaoShi.gif\" width=\"40\" height=\"48\" border=\"0\" alt=\"\" /></a></div>";
s_footer += "		<p><a href=\"http://www.csdn.net/intro/intro.asp?id=2\">网站简介</a>－<a href=\"http://www.csdn.net/intro/intro.asp?id=5\">广告服务</a>－<a href=\"http://www.csdn.net/map/map.shtm\">网站地图</a>－<a href=\"http://www.csdn.net/help/help.asp\">帮助信息</a>－<a href=\"http://www.csdn.net/intro/intro.asp?id=9\">联系方式</a>－<a href=\"http://www.csdn.net/english/\">English</a>－<a href=\"mailto:webmaster@csdn.net\">问题报告</a></p>";
s_footer += "		<p><a href=\"http://community.csdn.net/tree/treenodeData/sitemap.htm\"><font color=\"#ffffff\">CSDN</font></a>北京百联美达美数码科技有限公司&nbsp;&nbsp;版权所有&nbsp;&nbsp;京 ICP 证 020026 号 <a href=\"http://community.csdn.net/tree/treenodeData/sitemap.htm\"><font color=\"#ffffff\">CSDN</font></a></p>";
s_footer += "		<p>&copy; 2000-04, CSDN.NET, All Rights Reserved</p>";
s_footer += "	</div>";
s_footer += "	<hr align=\"center\" />";
s_footer += "</div>";

s_footer += "<script src=\"http://www.csdn.net/common/counter.js\"></s"+"cript>";
document.write(s_footer);